version: "2"
services:
  web:
    build: .
    ports:
      - '80:80'
    # environment:
    #   - PORT=
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: tagesstaette
