version: "2"
services:
  web:
    build: .
    # ports:
    #   - '80:80'
    networks:
      - my_network

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: j_tasks
    networks:
      my_network:
        aliases:
          - mariadb
