version: "2"
services:
  web:
    build: .
    networks:
      - my_network
    environment:
      DB_HOST: ""

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: tagesstaette
    networks:
      my_network:
        aliases:
          - mariadb

networks:
  my_network:
